"""
backend/export_pdf.py — Generate a PDF booklet from a completed story.

Each page contains:
- Illustration (if available)
- Story text for that scene
- Choice made (if not the final scene)

The PDF is designed to be printable and re-uploadable for RAG.
"""

from __future__ import annotations

import base64
import io
from typing import Any

from reportlab.lib.pagesizes import A5
from reportlab.lib.units import mm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    PageBreak,
)
from reportlab.lib.colors import HexColor


def generate_story_pdf(
    child_name: str,
    story_idea: str,
    scenes: list[dict[str, Any]],
) -> bytes:
    """
    Generate a PDF booklet from story scenes.

    Each scene dict should have:
    - story_text: str
    - illustration_b64: str (base64 encoded image, optional)
    - step_number: int
    - is_ending: bool
    - choice_made: str (the choice text the child selected, empty for last scene)
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A5,
        topMargin=15 * mm,
        bottomMargin=15 * mm,
        leftMargin=12 * mm,
        rightMargin=12 * mm,
    )

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        "StoryTitle",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=18,
        textColor=HexColor("#2c1810"),
        alignment=TA_CENTER,
        spaceAfter=6 * mm,
    )

    subtitle_style = ParagraphStyle(
        "StorySubtitle",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=10,
        textColor=HexColor("#8b4513"),
        alignment=TA_CENTER,
        spaceAfter=10 * mm,
    )

    body_style = ParagraphStyle(
        "StoryBody",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=11,
        leading=15,
        textColor=HexColor("#1a1a2e"),
        alignment=TA_JUSTIFY,
        spaceAfter=4 * mm,
    )

    choice_style = ParagraphStyle(
        "ChoiceMade",
        parent=styles["Normal"],
        fontName="Helvetica-Oblique",
        fontSize=9,
        textColor=HexColor("#6b3a1f"),
        alignment=TA_CENTER,
        spaceBefore=4 * mm,
    )

    page_num_style = ParagraphStyle(
        "PageNum",
        parent=styles["Normal"],
        fontName="Helvetica",
        fontSize=8,
        textColor=HexColor("#999999"),
        alignment=TA_CENTER,
    )

    elements = []

    # ── Cover page ────────────────────────────────────────────────────────────
    elements.append(Spacer(1, 30 * mm))
    elements.append(Paragraph(f"A Story for {child_name}", title_style))
    elements.append(Paragraph(f'"{story_idea}"', subtitle_style))
    elements.append(Spacer(1, 10 * mm))
    elements.append(
        Paragraph(
            "Generated by Dream Weaver",
            ParagraphStyle("Credit", parent=styles["Normal"], fontSize=8, alignment=TA_CENTER, textColor=HexColor("#aaa")),
        )
    )

    # First scene illustration as cover image (if available)
    if scenes and scenes[0].get("illustration_b64"):
        try:
            img_data = base64.b64decode(scenes[0]["illustration_b64"])
            img = Image(io.BytesIO(img_data))
            page_width = A5[0] - 24 * mm
            aspect = img.imageWidth / img.imageHeight if img.imageHeight else 1
            img_width = min(page_width, 100 * mm)
            img_height = img_width / aspect
            img.drawWidth = img_width
            img.drawHeight = img_height
            elements.append(Spacer(1, 8 * mm))
            elements.append(img)
        except Exception:
            pass

        if i < len(scenes) - 1:
            elements.append(PageBreak())

    # ── Story pages ───────────────────────────────────────────────────────────
    for i, scene in enumerate(scenes):
        text = scene.get("story_text", "")
        illustration = scene.get("illustration_b64", "")
        choice_made = scene.get("choice_made", "")
        step = scene.get("step_number", i)

        # Illustration
        if illustration:
            try:
                img_data = base64.b64decode(illustration)
                img = Image(io.BytesIO(img_data))
                page_width = A5[0] - 24 * mm
                aspect = img.imageWidth / img.imageHeight if img.imageHeight else 1
                img_width = min(page_width, 100 * mm)
                img_height = img_width / aspect
                img.drawWidth = img_width
                img.drawHeight = img_height
                elements.append(img)
                elements.append(Spacer(1, 4 * mm))
            except Exception:
                pass

        # Story text
        safe_text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        elements.append(Paragraph(safe_text, body_style))

        # Choice made (except for ending)
        if choice_made:
            elements.append(
                Paragraph(f'→ {child_name} chose: "{choice_made}"', choice_style)
            )

        # Page number
        elements.append(Spacer(1, 6 * mm))
        elements.append(Paragraph(f"— {step + 1} —", page_num_style))

        if i < len(scenes) - 1:
            elements.append(PageBreak())

    doc.build(elements)
    return buf.getvalue()
